version: '3.5'

networks:
  kraken:
    name: "kraken"

services:

  kraken-influxdb-dev:
    image: influxdb:1.7.4
    container_name: kraken-influxdb-dev
    ports:
      - "8086:8086"
#      - "8083:8083"
#      - "8090:8090"
#      - "2003:2003"
    expose:
      - "8086"
    env_file:
      - 'influxdb/env.influxdb'
    volumes:
      - ./analysis/influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    networks:
      - kraken

  kraken-analysis-telegraf-dev:
    user: ${KRAKEN_HOST_UID}:${KRAKEN_HOST_GID}
    image: telegraf:1.10.0
    container_name: kraken-analysis-telegraf-dev
    networks:
      - kraken
    env_file:
      - 'telegraf/env.telegraf'
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - kraken-influxdb-dev

  kraken-grafana-dev:
    user: ${KRAKEN_HOST_UID}:${KRAKEN_HOST_GID}
    image: grafana/grafana:5.4.3
    container_name: kraken-grafana-dev
    ports:
      - "3000:3000"
    env_file:
      - 'grafana/env.grafana'
    networks:
      - kraken
    volumes:
      - ./analysis/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro