version: '3.5'

services:
  kraken-har-parser:
    image: octoperf/kraken-ee-har-parser:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-har-parser_STARTING
    network_mode: host
    labels:
      com.kraken/taskId: ${KRAKEN_TASK_ID}
      com.kraken/taskType: RECORD
      com.kraken/containerId: ${KRAKEN_TASK_ID}-har-parser
      com.kraken/hostId: local
      com.kraken/name: HAR Parser
      com.kraken/description: ${KRAKEN_DESCRIPTION}
      com.kraken/expectedCount: ${KRAKEN_EXPECTED_COUNT}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-har-parser
      KRAKEN_HOST_ID: local
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"

  kraken-gatling-recorder:
    image: octoperf/kraken-gatling-recorder:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-recorder_STARTING
    network_mode: host
    labels:
      com.kraken/taskId: ${KRAKEN_TASK_ID}
      com.kraken/taskType: RECORD
      com.kraken/containerId: ${KRAKEN_TASK_ID}-gatling-recorder
      com.kraken/hostId: local
      com.kraken/name: Gatling Recorder
      com.kraken/description: ${KRAKEN_DESCRIPTION}
      com.kraken/expectedCount: ${KRAKEN_EXPECTED_COUNT}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-gatling-recorder
      KRAKEN_HOST_ID: local
      KRAKEN_GATLING_SIMULATION_CLASS: ${KRAKEN_GATLING_SIMULATION_CLASS}
      KRAKEN_GATLING_SIMULATION_PACKAGE: ${KRAKEN_GATLING_SIMULATION_PACKAGE}
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"