version: '3.5'

services:
  kraken-gatling-telegraf:
    image: octoperf/kraken-telegraf:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-telegraf_STARTING
    network_mode: host
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: RUN
      com.kraken.containerId: ${KRAKEN_TASK_ID}-gatling-telegraf
      com.kraken.groupId: local
      com.kraken.name: Telegraf
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RUN
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-gatling-telegraf
      KRAKEN_GROUP_ID: local
      KRAKEN_INFLUXDB_URL: ${KRAKEN_INFLUXDB_URL}
      KRAKEN_INFLUXDB_DATABASE: ${KRAKEN_INFLUXDB_DATABASE}
      KRAKEN_INFLUXDB_USER: ${KRAKEN_INFLUXDB_USER}
      KRAKEN_INFLUXDB_PASSWORD: ${KRAKEN_INFLUXDB_PASSWORD}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"

  kraken-gatling-runner:
    image: octoperf/kraken-gatling-runner:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-runner_STARTING
    network_mode: host
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: RUN
      com.kraken.containerId: ${KRAKEN_TASK_ID}-gatling-runner
      com.kraken.groupId: local
      com.kraken.name: Gatling Runner
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RUN
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-gatling-runner
      KRAKEN_GROUP_ID: local
      KRAKEN_GATLING_SIMULATION: ${KRAKEN_GATLING_SIMULATION}
      KRAKEN_GATLING_DESCRIPTION: ${KRAKEN_DESCRIPTION}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"
