version: '3.5'

networks:
  kraken:
    name: ${KRAKEN_DOCKER_NETWORK_NAME}
    external: ${KRAKEN_DOCKER_NETWORK_EXTERNAL}

services:
  kraken-gatling-log-parser:
    image: octoperf/kraken-ee-gatling-log-parser:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-log-parser_STARTING
    networks:
      - kraken
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: DEBUG
      com.kraken.containerId: ${KRAKEN_TASK_ID}-gatling-log-parser
      com.kraken.groupId: local
      com.kraken.name: Gatling Logs Parser
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: DEBUG
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-gatling-log-parser
      KRAKEN_GROUP_ID: local
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - kraken-gatling-debugger

  kraken-gatling-debugger:
    image: octoperf/kraken-gatling-runner:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-debugger_STARTING
    networks:
      - kraken
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: DEBUG
      com.kraken.containerId: ${KRAKEN_TASK_ID}-gatling-debugger
      com.kraken.groupId: local
      com.kraken.name: Gatling Runner
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: DEBUG
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-gatling-debugger
      KRAKEN_GROUP_ID: local
      KRAKEN_GATLING_SIMULATION: ${KRAKEN_GATLING_SIMULATION}
      KRAKEN_GATLING_DESCRIPTION: ${KRAKEN_DESCRIPTION}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"
    volumes:
      - type: volume
        source: gatling-volume
        target: /kraken/gatling/results

volumes:
  gatling-volume:
    name: ${KRAKEN_TASK_ID}-gatling-volume