version: '3.5'

networks:
  kraken:
    name: kraken
    external: true

services:
  kraken-har-parser:
    image: octoperf/kraken-har-parser:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-har-parser_STARTING
    networks:
      - kraken
    labels:
      com.kraken/taskId: ${KRAKEN_TASK_ID}
      com.kraken/taskType: RECORD
      com.kraken/containerName: ${KRAKEN_TASK_ID}-har-parser
      com.kraken/hostId: local
      com.kraken/label: HAR Parser
      com.kraken/description: ${KRAKEN_DESCRIPTION}
      com.kraken/expectedCount: ${KRAKEN_EXPECTED_COUNT}
      com.kraken/applicationId: ${KRAKEN_APPLICATION_ID}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_NAME: ${KRAKEN_TASK_ID}-har-parser
      KRAKEN_HOST_ID: local
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"

  kraken-gatling-recorder:
    image: octoperf/kraken-gatling-recorder:${KRAKEN_VERSION}
    container_name: ${KRAKEN_TASK_ID}-gatling-recorder_STARTING
    networks:
      - kraken
    labels:
      com.kraken/taskId: ${KRAKEN_TASK_ID}
      com.kraken/taskType: RECORD
      com.kraken/containerName: ${KRAKEN_TASK_ID}-gatling-recorder
      com.kraken/hostId: local
      com.kraken/label: Gatling Recorder
      com.kraken/description: ${KRAKEN_DESCRIPTION}
      com.kraken/expectedCount: ${KRAKEN_EXPECTED_COUNT}
      com.kraken/applicationId: ${KRAKEN_APPLICATION_ID}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_NAME: ${KRAKEN_TASK_ID}-gatling-recorder
      KRAKEN_HOST_ID: local
      KRAKEN_GATLING_SIMULATION_CLASS: ${KRAKEN_GATLING_SIMULATION_CLASS}
      KRAKEN_GATLING_SIMULATION_PACKAGE: ${KRAKEN_GATLING_SIMULATION_PACKAGE}
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_GATLING_JAVA_OPTS: ${KRAKEN_GATLING_JAVA_OPTS}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}
      JAVA_OPTS: "-Dspring.profiles.active=docker"