version: '3.5'

services:
  kraken-gatling-recorder:
    image: "octoperf/kraken-gatling-recorder:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}_STARTING"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "${GATLING_CPU_LIMIT}"
          memory: "${GATLING_MEMORY_LIMIT}"
        reservations:
          cpus: "${GATLING_CPU_REQUEST}"
          memory: "${GATLING_MEMORY_REQUEST}"
    labels:
      com.kraken/taskId: "${KRAKEN_TASK_ID}"
      com.kraken/taskType: "${KRAKEN_TASK_TYPE}"
      com.kraken/containerName: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      com.kraken/hostId: "${KRAKEN_HOST_ID}"
      com.kraken/label: "${KRAKEN_GATLING_CONTAINER_LABEL}"
      com.kraken/description: "${KRAKEN_DESCRIPTION}"
      com.kraken/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.kraken/applicationId: "${KRAKEN_APPLICATION_ID}"
    environment:
      KRAKEN_TASK_ID: "${KRAKEN_TASK_ID}"
      KRAKEN_TASK_TYPE: "${KRAKEN_TASK_TYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_CONTAINER_NAME}"
      KRAKEN_HOST_ID: "${KRAKEN_HOST_ID}"
      KRAKEN_GATLING_SIMULATION_CLASS: "${KRAKEN_GATLING_SIMULATION_CLASS}"
      KRAKEN_GATLING_SIMULATION_PACKAGE: "${KRAKEN_GATLING_SIMULATION_PACKAGE}"
      KRAKEN_GATLING_HAR_PATH_REMOTE: "${KRAKEN_GATLING_HAR_PATH_REMOTE}"
      KRAKEN_GATLING_JAVA_OPTS: "${KRAKEN_GATLING_JAVA_OPTS} -Xmx${KRAKEN_GATLING_XMX}"
      KRAKEN_RUNTIME_URL: "${KRAKEN_RUNTIME_URL}"
      KRAKEN_STORAGE_URL: "${KRAKEN_STORAGE_URL}"
      KRAKEN_ANALYSIS_URL: "${KRAKEN_ANALYSIS_URL}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_GATLING_XMX}"

  kraken-har-parser:
    image: "octoperf/kraken-har-parser:${KRAKEN_VERSION}"
    container_name: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}_STARTING"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "${SIDEKICK_CPU_LIMIT}"
          memory: "${SIDEKICK_MEMORY_LIMIT}"
        reservations:
          cpus: "${SIDEKICK_CPU_REQUEST}"
          memory: "${SIDEKICK_MEMORY_REQUEST}"
    labels:
      com.kraken/taskId: "${KRAKEN_TASK_ID}"
      com.kraken/taskType: "${KRAKEN_TASK_TYPE}"
      com.kraken/containerName: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      com.kraken/hostId: "${KRAKEN_HOST_ID}"
      com.kraken/label: "${KRAKEN_GATLING_SIDEKICK_LABEL}"
      com.kraken/description: "${KRAKEN_DESCRIPTION}"
      com.kraken/expectedCount: "${KRAKEN_EXPECTED_COUNT}"
      com.kraken/applicationId: "${KRAKEN_APPLICATION_ID}"
    environment:
      KRAKEN_TASK_ID: "${KRAKEN_TASK_ID}"
      KRAKEN_TASK_TYPE: "${KRAKEN_TASK_TYPE}"
      KRAKEN_CONTAINER_NAME: "${KRAKEN_TASK_ID}-${KRAKEN_GATLING_SIDEKICK_NAME}"
      KRAKEN_HOST_ID: "${KRAKEN_HOST_ID}"
      KRAKEN_RUNTIME_URL: "${KRAKEN_RUNTIME_URL}"
      KRAKEN_STORAGE_URL: "${KRAKEN_STORAGE_URL}"
      KRAKEN_ANALYSIS_URL: "${KRAKEN_ANALYSIS_URL}"
      KRAKEN_GATLING_HAR_PATH_REMOTE: "${KRAKEN_GATLING_HAR_PATH_REMOTE}"
      JAVA_OPTS: "-Dspring.profiles.active=docker -Xmx${KRAKEN_SIDEKICK_XMX}"