version: '3.5'

networks:
  kraken:
    name: "kraken"

services:
  kraken-har-parser:
    image: octoperf/kraken-ee-har-parser:${KRAKEN_VERSION}
    container_name: kraken-har-parser
    networks:
      - kraken
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: RECORD
      com.kraken.containerId: ${KRAKEN_TASK_ID}-log-parser
      com.kraken.groupId: local
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-telegraf
      KRAKEN_GROUP_ID: local
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}

  kraken-gatling-recorder:
    image: octoperf/kraken-gatling-recorder:${KRAKEN_VERSION}
    container_name: kraken-gatling-recorder
    networks:
      - kraken
    labels:
      com.kraken.taskId: ${KRAKEN_TASK_ID}
      com.kraken.taskType: RECORD
      com.kraken.containerId: ${KRAKEN_TASK_ID}-log-parser
      com.kraken.groupId: local
      com.kraken.description: ${KRAKEN_DESCRIPTION}
    environment:
      KRAKEN_TASK_ID: ${KRAKEN_TASK_ID}
      KRAKEN_TASK_TYPE: RECORD
      KRAKEN_CONTAINER_ID: ${KRAKEN_TASK_ID}-telegraf
      KRAKEN_GROUP_ID: local
      KRAKEN_GATLING_SIMULATION_CLASS: ${KRAKEN_GATLING_SIMULATION_CLASS}
      KRAKEN_GATLING_SIMULATION_PACKAGE: ${KRAKEN_GATLING_SIMULATION_PACKAGE}
      KRAKEN_GATLING_HAR_PATH_REMOTE: ${KRAKEN_GATLING_HAR_PATH_REMOTE}
      KRAKEN_ANALYSIS_URL: ${KRAKEN_ANALYSIS_URL}
      KRAKEN_RUNTIME_URL: ${KRAKEN_RUNTIME_URL}
      KRAKEN_STORAGE_URL: ${KRAKEN_STORAGE_URL}