apiVersion: 1

datasources:
- name: Analysis Server
  orgId: 1
  type: influxdb
  access: proxy
  url: http://kraken-influxdb-dev:8086
  database: analysis-server
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: kraken
- name: Gatling
  orgId: 1
  type: influxdb
  access: proxy
  url: http://kraken-influxdb-dev:8086
  database: gatling
  isDefault: true
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: user
  basicAuthPassword: kraken