version: '3.5'

networks:
  kraken:
    name: "kraken"

services:
  kraken-gatling-telegraf:
    user: ${KRAKEN_HOST_UID}:${KRAKEN_HOST_GID}
    image: telegraf:1.10.0
    container_name: kraken-gatling-telegraf
    networks:
      - kraken
    environment:
      KRAKEN_TEST_ID: ${KRAKEN_TEST_ID}
      INFLUXDB_URL: ${KRAKEN_INFLUXDB_URL}
      INFLUXDB_DB: ${KRAKEN_INFLUXDB_DATABASE}
      INFLUXDB_USER: ${KRAKEN_INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${KRAKEN_INFLUXDB_PASSWORD}
    volumes:
      - ${KRAKEN_HOST_DATA}/gatling/runner/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  kraken-gatling-runner:
    image: octoperf/kraken-gatling-runner:3.0.3
    container_name: kraken-gatling-runner
    networks:
      - kraken
    environment:
      KRAKEN_HOST_UID: ${KRAKEN_HOST_UID}
      KRAKEN_HOST_GID: ${KRAKEN_HOST_GID}
      KRAKEN_HOST_DATA: ${KRAKEN_HOST_DATA}
      JAVA_OPTS: ${JAVA_OPTS}
    volumes:
      - ${KRAKEN_HOST_DATA}/gatling/conf/run:/kraken/gatling/conf
      - ${KRAKEN_HOST_DATA}/gatling/user-files:/kraken/gatling/user-files
      - ${KRAKEN_HOST_DATA}/gatling/results:/kraken/gatling/results
    command: ${GATLING_COMMAND}
    depends_on:
      - kraken-gatling-telegraf
