kraken:
  runtime:
    containers-count:
      run: 2
      debug: 2
      record: 2
    resources-allocation:
      run:
        gatling:
          cpu:
            request: "1"
            limit: "2"
          memory:
            request: "512M"
            limit: "1024M"
        telegraf:
          cpu:
            request: "0.5"
            limit: "1"
          memory:
            request: "128M"
            limit: "256M"
      debug:
        gatling:
          cpu:
            request: "1"
            limit: "2"
          memory:
            request: "512M"
            limit: "1024M"
        log-parser:
          cpu:
            request: "0.5"
            limit: "1"
          memory:
            request: "256M"
            limit: "512M"
      record:
        gatling:
          cpu:
            request: "0.5"
            limit: "1"
          memory:
            request: "512M"
            limit: "1024M"
        har-parser:
          cpu:
            request: "0.5"
            limit: "1"
          memory:
            request: "512M"
            limit: "1024M"
  influxdb:
    user: admin
    password: kraken
    database: gatling

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 1MB # Max file size.
      max-request-size: 10MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8082
  error:
    include-stacktrace: always

---
spring:
  profiles: dev

kraken:
  data: devData/
  storage:
    url: http://localhost:8080
  analysis:
    url: http://localhost:8081
  runtime:
    url: http://localhost:8082
  influxdb:
    url: http://localhost:8086

---
spring:
  profiles: docker

kraken:
  data: /home/kraken/data
  storage:
    url: http://kraken-storage:8080
  analysis:
    url: http://kraken-analysis:8081
  runtime:
    url: http://kraken-runtime:8082
  influxdb:
    url: http://kraken-influxdb:8086