version: '3.7'

services:
  kraken-postgres:
    image: postgres:12.2
    container_name: kraken-postgres-dev
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  kraken-keycloak:
    image: quay.io/keycloak/keycloak:9.0.2
    container_name: kraken-keycloak-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: kraken-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: kraken
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
    ports:
      - 9080:8080
    expose:
      - 9080
    depends_on:
      - kraken-postgres
    command:
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/kraken-realm.json"