spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 1MB # Max file size.
      max-request-size: 10MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8083
  error:
    include-stacktrace: always

---
spring:
  profiles: dev

kraken:
  storage:
    url: http://localhost:8080
  runtime:
    url: http://localhost:8082

---
spring:
  profiles: docker

kraken:
  storage:
    url: http://kraken-storage:8080
  runtime:
    url: http://kraken-runtime:8082