metadata:
  annotations:
    com.kraken/description: description
    com.kraken/expectedCount: '2'
  labels:
    com.kraken/taskType: RECORD
    com.kraken/hostId: hostId
    com.kraken/taskId: taskId
    com.kraken/applicationId: applicationId
  name: applicationid-record-taskid-id
spec:
  containers:
  - env:
    - name: JAVA_OPTS
      value: -Dspring.profiles.active=kubernetes
    - name: KRAKEN_TASK_ID
      value: taskId
    - name: KRAKEN_TASK_TYPE
      value: RECORD
    - name: KRAKEN_HOST_ID
      value: hostId
    - name: KRAKEN_CONTAINER_NAME
      value: applicationid-record-taskid-hostId-gatling-recorder
    - name: KRAKEN_DESCRIPTION
      value: description
    - name: KRAKEN_CONTAINER_LABEL
      value: Gatling Recorder
    - name: key
      value: value
    - name: foo
      value: bar
    - name: KRAKEN_GATLING_JAVA_OPTS
      value: -Dfoo="bar"
    - name: KRAKEN_STORAGE_URL
      value: storageUrl
    - name: KRAKEN_RUNTIME_URL
      value: runtimeUrl
    - name: KRAKEN_ANALYSIS_URL
      value: analysisUrl
    image: octoperf/kraken-gatling-recorder:1.3.0
    name: applicationid-record-taskid-hostId-gatling-recorder
  - env:
    - name: JAVA_OPTS
      value: -Dspring.profiles.active=kubernetes
    - name: KRAKEN_TASK_ID
      value: taskId
    - name: KRAKEN_TASK_TYPE
      value: RECORD
    - name: KRAKEN_HOST_ID
      value: hostId
    - name: KRAKEN_CONTAINER_NAME
      value: applicationid-record-taskid-hostId-har-parser
    - name: KRAKEN_DESCRIPTION
      value: description
    - name: KRAKEN_CONTAINER_LABEL
      value: HAR Parser
    - name: key
      value: value
    - name: foo
      value: bar
    - name: KRAKEN_ANALYSIS_URL
      value: analysisUrl
    - name: KRAKEN_STORAGE_URL
      value: storageUrl
    - name: KRAKEN_RUNTIME_URL
      value: runtimeUrl
    image: octoperf/kraken-har-parser:1.3.0
    name: applicationid-record-taskid-hostId-har-parser
  nodeSelector:
    com.kraken/hostId: hostId
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
