kraken:
#  data: ../data/
#  host.data: /home/kraken/data
#  host.uid: 1001
#  host.gid: 1001
  command:
    url: http://localhost:8081

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 1MB # Max file size.
      max-request-size: 10MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8082
  error:
    include-stacktrace: always

---
spring:
  profiles: prod

kraken:
#  data: must be given using env variable KRAKEN_DATA
#  host.data: must be given as using env variable KRAKEN_HOST_DATA
#  host.uid: must be given as using env variable KRAKEN_HOST_UID
#  host.gid: must be given as using env variable KRAKEN_HOST_GID
  command:
    url: http://kraken-command:8081