kraken:
#  data: ../data/

spring:
  servlet:
    multipart:
      enabled: true # Whether to enable support of multipart uploads.
      file-size-threshold: 0B # Threshold after which files are written to disk.
      location: # Intermediate location of uploaded files.
      max-file-size: 1MB # Max file size.
      max-request-size: 10MB # Max request size.
      resolve-lazily: false # Whether to resolve the multipart request lazily at the time of file or parameter access.

logging:
  level:
    root: INFO
  com:
    kraken: INFO

server:
  port: 8080
  error:
    include-stacktrace: always

---
spring:
  profiles: prod

kraken:
#  data: must be given using env variable KRAKEN_DATA